### ISSUE TITLE
npm start doesn't work

### ISSUE THREAD

**Issue by hongkongkiwi** [doubleleft/hook-admin#7]

**Comment by endel** [comment]
Hey @hongkongkiwi, thanks for reporting this.

There isn't much documentation to this project yet, but basically you'll need to replace the sample [hook-ext](https://github.com/doubleleft/hook-admin/tree/master/hook-ext) directory with your own project hook configurations. 

Also there are many options available to override and configure here: https://github.com/doubleleft/hook-admin/blob/master/app/config/app.yaml

Please let me know if you find any trouble.

**Comment by endel** [comment]
@hongkongkiwi I've updated the README to make it clear how to set it up and running.
